export const REQUEST_RATES_LATEST = 'REQUEST_RATES_LATEST';
export const RECEIVE_RATES_LATEST = 'RECEIVE_RATES_LATEST';
export const REQUEST_ADD_NEW_CONVERSION = 'REQUEST_ADD_NEW_CONVERSION';
export const ADD_NEW_CONVERSION = 'ADD_NEW_CONVERSION';
export const RECEIVE_NEW_MAIN_CONVERSION_VALUE = 'RECEIVE_NEW_MAIN_CONVERSION_VALUE';
export const DELETE_NEW_CONVERSION = 'DELETE_NEW_CONVERSION';